### ISSUE TITLE
Illegal constructor

### ISSUE THREAD

**Issue by imperator-maximus** [shaozi/svelte-steps#43]
Hi,

I am using just the first test example inside a custom component and I am getting:

index.mjs:2162 Uncaught (in promise) TypeError: Illegal constructor
    at new SvelteElement (index.mjs:2162:13)
    at new Steps (Steps.svelte:107:23)
    at create_if_block_15 (FirstConfig.svelte:459:24)
    at Object.update [as p] (FirstConfig.svelte:270:49)
    at Object.update [as p] (FirstConfig.svelte:235:18)
    at update (index.mjs:1298:36)
    at flush (index.mjs:1258:17)

**Comment by shaozi** [comment]
Can you post some code on how do you use svelte-steps in order for people to help?
